name: Update Firestore Indexes

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  HUSKY: 0

jobs:
  update-indexes:
    name: Update Firestore Indexes from Dev
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install dependencies
        run: |
          npm install -g husky
          npm ci

      - name: Install Firebase CLI
        run: |
          npm install -g firebase-tools
        shell: bash

      - name: Authenticate with GCP (Dev)
        uses: google-github-actions/auth@v2
        with:
          project_id: hs-levante-admin-dev
          credentials_json: ${{ secrets.GCP_SA_CREDENTIALS_DEV }}
          request_reason: 'levante-firebase-functions/update-indexes run ${{ github.run_id }}'
          access_token_scopes: 'email,openid,https://www.googleapis.com/auth/cloudplatformprojects.readonly,https://www.googleapis.com/auth/firebase,https://www.googleapis.com/auth/cloud-platform'

      - name: Export current Firestore indexes from Dev
        run: |
          cd functions/levante-admin
          firebase firestore:indexes --project dev > current-indexes.json
        shell: bash

      - name: Check if indexes have changed
        id: check-changes
        run: |
          cd functions/levante-admin
          
          # Function to normalize JSON for comparison
          normalize_json() {
            jq -S '.' "$1" | sed 's/[[:space:]]//g'
          }
          
          # Check if firestore.indexes.json exists
          if [ ! -f "firestore.indexes.json" ]; then
            echo "firestore.indexes.json not found, will create it"
            echo "has-changes=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          # Normalize both files
          normalize_json "firestore.indexes.json" > local-normalized.json
          normalize_json "current-indexes.json" > remote-normalized.json
          
          # Compare the normalized files
          if cmp -s local-normalized.json remote-normalized.json; then
            echo "Indexes are up to date"
            echo "has-changes=false" >> $GITHUB_OUTPUT
          else
            echo "Indexes have changed"
            echo "has-changes=true" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Update index file
        if: steps.check-changes.outputs.has-changes == 'true'
        run: |
          cd functions/levante-admin
          cp current-indexes.json firestore.indexes.json
          echo "Updated firestore.indexes.json with latest indexes from dev project"
        shell: bash

      - name: Configure Git
        if: steps.check-changes.outputs.has-changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
        shell: bash

      - name: Create or switch to test-write-access branch
        if: steps.check-changes.outputs.has-changes == 'true'
        run: |
          # Check if branch exists
          if git ls-remote --heads origin test-write-access | grep -q test-write-access; then
            echo "Branch test-write-access exists, switching to it"
            git fetch origin test-write-access
            git checkout test-write-access
          else
            echo "Branch test-write-access does not exist, creating it"
            git checkout -b test-write-access
          fi
        shell: bash

      - name: Commit and push changes
        if: steps.check-changes.outputs.has-changes == 'true'
        run: |
          cd functions/levante-admin
          git add firestore.indexes.json
          git commit -m "🤖 Auto-update Firestore indexes from dev project

          - Updated indexes from hs-levante-admin-dev
          - Auto-generated by GitHub Actions
          - Triggered by merge to main
          - Committed to test-write-access branch"
          git push origin test-write-access
        shell: bash

      - name: Log success
        if: steps.check-changes.outputs.has-changes == 'true'
        run: |
          echo "✅ Successfully updated firestore.indexes.json with latest indexes from dev project"
          echo "📝 Changes have been committed to test-write-access branch"
        shell: bash

      - name: Log no changes
        if: steps.check-changes.outputs.has-changes == 'false'
        run: |
          echo "✅ Indexes are already up to date"
          echo "📝 No changes needed"
        shell: bash

      - name: Cleanup
        if: always()
        run: |
          cd functions/levante-admin
          rm -f current-indexes.json local-normalized.json remote-normalized.json
        shell: bash